// Full backend flows against a real OMP process and a local deterministic provider.
import http from 'node:http';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,mkdir,writeFile,readFile,rm,stat} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {fileURLToPath} from 'node:url';
const root=await mkdtemp(path.join(os.tmpdir(),'pi-parity-'));const project=path.join(root,'Projekt ä');await mkdir(project);const proof=path.join(project,'proof.txt');let releaseHold,held=false,requests=[];
const model=http.createServer(async(req,res)=>{try{let raw='';for await(const b of req)raw+=b;const input=JSON.parse(raw||'{}');const ms=input.messages||[],lastUser=ms.findLastIndex(m=>m.role==='user');const message=ms[lastUser]?.content;const text=typeof message==='string'?message:JSON.stringify(message);requests.push(text);if(text.includes('HOLD')){held=true;await new Promise(r=>releaseHold=r);}const needsWrite=text.includes('WRITE')&&!ms.slice(lastUser+1).some(m=>m.role==='tool');const tool=input.tools?.find(t=>t.function?.name==='write');const delta=needsWrite&&tool?{role:'assistant',tool_calls:[{index:0,id:'call_'+Date.now(),type:'function',function:{name:'write',arguments:JSON.stringify({path:proof,content:text})}}]}:{role:'assistant',content:'Fixture abgeschlossen: '+text};res.writeHead(200,{'Content-Type':'text/event-stream'});for(const d of [delta,{}])res.write('data: '+JSON.stringify({id:'fixture',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta:d,finish_reason:Object.keys(d).length?null:needsWrite&&tool?'tool_calls':'stop'}]})+'\n\n');res.end('data: [DONE]\n\n');}catch(e){res.destroy(e);}});
await new Promise(r=>model.listen(0,'127.0.0.1',r));let server,origin,taskId;const token='isolated-fixture';
const wait=async fn=>{const until=Date.now()+25000;while(Date.now()<until){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,80));}throw Error('Condition timed out');};
async function start(){server=spawn(process.execPath,[fileURLToPath(new URL('../server.mjs',import.meta.url))],{env:{...process.env,PI_DESK_NATIVE_TOKEN:token,PI_DESK_PORT:'0',PI_DESK_DATA:path.join(root,'data')},stdio:['pipe','pipe','pipe']});let errors='';server.stderr.on('data',b=>errors+=b);origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error(errors||'Server timeout')),10000);server.stdout.once('data',b=>{clearTimeout(t);resolve(String(b).trim().replace('Pi Desk ',''));});server.once('exit',()=>{clearTimeout(t);reject(Error(errors));});});}
async function stop(){if(!server||server.exitCode!==null)return;const exited=new Promise(r=>server.once('exit',r));server.stdin.end();await exited;}
async function api(route,body){const r=await fetch(origin+'/api/'+route,{method:body?'POST':'GET',headers:{'X-Pi-Desk-Native':token,...(body?{Origin:origin,'X-Pi-Desk':'1','Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const j=await r.json();assert.equal(r.status,200,JSON.stringify(j));return j;}
const session=()=>api('session?taskId='+taskId);
try{
 await start();const p=await api('projects',{path:project});taskId=(await api('tasks',{projectId:p.id})).id;
 const c=await api('settings/connection',{name:'Fixture',kind:'openai',baseUrl:`http://127.0.0.1:${model.address().port}/v1`,models:['fixture'],apiKey:'local-fixture'});
 const models=(await api('models?taskId='+taskId)).models;const m=models.find(m=>m.id==='fixture');assert.ok(m);await api('model',{taskId,provider:m.provider,modelId:m.id});
 await api('prompt',{taskId,message:'WRITE ONE',context:[]});let pending=await wait(async()=> (await session()).pending[0]);assert.match(pending.title+'\n'+pending.message,/Allow tool: write/);await assert.rejects(stat(proof));await api('respond',{taskId,id:pending.id,...(pending.method==='confirm'?{confirmed:false}:{value:'Deny'})});await wait(async()=>!(await session()).busy);await assert.rejects(stat(proof));
 await api('prompt',{taskId,message:'WRITE TWO',context:[]});pending=await wait(async()=> (await session()).pending[0]);await api('respond',{taskId,id:pending.id,scope:'chat',...(pending.method==='confirm'?{confirmed:true}:{value:'Approve'})});await wait(async()=>!(await session()).busy);assert.match(await readFile(proof,'utf8'),/WRITE TWO/);
 await stop();await start();await api('prompt',{taskId,message:'WRITE THREE',context:[]});await wait(async()=>!(await session()).busy);assert.match(await readFile(proof,'utf8'),/WRITE THREE/);assert.ok((await api('desktop-settings')).approvals.chats[taskId].includes('write'));console.log('PASS deny, explicit chat approval, restart persistence and automatic write approval');
 await api('prompt',{taskId,message:'HOLD',context:[]});await wait(()=>held);
 const removed=await api('follow-up',{taskId,message:'MUST_NOT_EXECUTE',context:[]});await api('queue-remove',{taskId,id:removed.item.id});await api('follow-up',{taskId,message:'/help',context:[]});await api('follow-up',{taskId,message:'FOLLOWUP_EXECUTES',context:[]});releaseHold();await wait(async()=>{const s=await session();return !s.busy&&!s.queue.length&&s.messages.some(m=>JSON.stringify(m).includes('FOLLOWUP_EXECUTES'));});assert.ok(!requests.some(x=>x.includes('MUST_NOT_EXECUTE')));assert.ok(requests.some(x=>x.includes('FOLLOWUP_EXECUTES')));console.log('PASS removed queued message never reaches model; retained message runs');
 const exp=await api('export',{taskId});assert.ok((await stat(exp.path)).size>0);
 const branches=await api('branches?taskId='+taskId);console.log('Branch entry shape:',JSON.stringify(branches.messages?.[0]));
 if(branches.messages?.length){const entry=branches.messages[0];const branch=await api('branch',{taskId,entryId:entry.id||entry.entryId});assert.notEqual(branch.sessionFile,(await session()).task.sessionFile);console.log('PASS independent real session branch');}
 const handoffResponse=await fetch(origin+'/api/handoff',{method:'POST',headers:{'X-Pi-Desk-Native':token,Origin:origin,'X-Pi-Desk':'1','Content-Type':'application/json'},body:JSON.stringify({taskId})});const handoff=await handoffResponse.json();if(handoffResponse.ok){assert.ok(handoff.path);assert.ok((await stat(handoff.path)).size>0);console.log('PASS real handoff file');}else{assert.match(handoff.error,/Nothing to hand off/);console.log('PASS handoff exposes OMP short-session refusal without inventing an export');}
 const source=(await session()).task.sessionFile;const imported=await api('tasks',{projectId:p.id,sessionFile:source});assert.notEqual(imported.sessionFile,source);assert.ok((await stat(source)).size>0);console.log('PASS real HTML export and independent session import');
 await api('approvals-clear',{});assert.deepEqual((await api('desktop-settings')).approvals,{global:[],chats:{}});
}catch(e){console.error('REQUESTS',requests);throw e;}finally{releaseHold?.();await stop();model.closeAllConnections();await new Promise(r=>model.close(r));await rm(root,{recursive:true,force:true});}
