import {realpath,stat,readdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile);
export async function contained(root,relative){if(typeof relative!=='string'||path.isAbsolute(relative)||relative.includes('\0'))throw Error('Ungültiger Dateipfad');const base=await realpath(root),file=await realpath(path.resolve(base,relative));if(file!==base&&!file.startsWith(base+path.sep))throw Error('Datei liegt außerhalb des Projekts');return file;}
export async function textFile(root,relative){const file=await contained(root,relative),s=await stat(file);if(!s.isFile()||s.size>250000)throw Error('Nur Textdateien bis 250 KB');const b=await readFile(file);if(b.includes(0))throw Error('Binärdatei kann nicht als Text angezeigt werden');return new TextDecoder('utf-8',{fatal:true}).decode(b);}
export async function listFiles(root,relative=''){const dir=await contained(root,relative),entries=await readdir(dir,{withFileTypes:true});return entries.filter(e=>!['.git','node_modules','.env','.DS_Store'].includes(e.name)&&!e.name.startsWith('.env.')).map(e=>({name:e.name,path:path.posix.join(relative,e.name),directory:e.isDirectory(),symlink:e.isSymbolicLink()})).sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name)).slice(0,500);}
export async function gitChanges(root){const run=async args=>(await exec('git',['-C',root,'--no-pager',...args],{maxBuffer:2e6,timeout:10000,env:{...process.env,GIT_OPTIONAL_LOCKS:'0'}})).stdout;try{const branch=(await run(['branch','--show-current'])).trim();const status=await run(['status','--short']);const unstaged=await run(['diff','--no-ext-diff','--no-textconv']);const staged=await run(['diff','--cached','--no-ext-diff','--no-textconv']);return {branch,status,diff:[staged&&'Vorgemerkt\n'+staged,unstaged&&'Arbeitsverzeichnis\n'+unstaged].filter(Boolean).join('\n\n')};}catch{return {branch:'',status:'',diff:'Kein Git-Diff verfügbar.'};}}
