import {readdir,readFile,writeFile,mkdir,realpath,stat,rename,rm,statfs,access} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';import http from 'node:http';import net from 'node:net';
import {spawn} from 'node:child_process';import {createHash,randomBytes,randomUUID} from 'node:crypto';
const GiB=1024**3;
export const runtimeSources={
 gguf:{url:'https://github.com/ggml-org/llama.cpp/releases/download/b11013/llama-b11013-bin-macos-arm64.tar.gz',sha:'e6e0c82862f409d2250e077562177caccf4fc0ff33ed712701aca902a531bd51'},
 winCPU:{url:'https://github.com/ggml-org/llama.cpp/releases/download/b11013/llama-b11013-bin-win-cpu-x64.zip',sha:'483545de333102de081f4c8b2b57b46dd360529d133ac993493e76aab7ad728f'},
 winVulkan:{url:'https://github.com/ggml-org/llama.cpp/releases/download/b11013/llama-b11013-bin-win-vulkan-x64.zip',sha:'09813058c66de72ffb0bdfd6a8c60dd229c280598c8922ec9b8cf66946268d2e'},
 uv:{url:'https://github.com/astral-sh/uv/releases/download/0.12.15/uv-aarch64-apple-darwin.tar.gz',sha:'dc304b9ed1b24174572290fba60ac3f6fe63c73a671f0439e62a91375841964d'}
};
const exists=async p=>{try{await access(p);return true;}catch{return false;}};
const atomic=async(p,o)=>{await writeFile(p+'.tmp',JSON.stringify(o,null,2),{mode:0o600});await rename(p+'.tmp',p);};
const hash=s=>createHash('sha256').update(s).digest('hex').slice(0,24);
export function suitability(bytes,memory=os.totalmem()){if(!bytes)return {fit:'Größe unbekannt',rank:3};const estimate=bytes*1.25+2*GiB;return estimate<memory*0.65?{fit:'Gute Speicherreserve',rank:0}:estimate<memory*0.85?{fit:'Knapp bemessen',rank:1}:{fit:'Voraussichtlich zu groß',rank:2};}
function safeRepo(id){if(typeof id!=='string'||! /^[\w.-]+\/[\w.-]+$/.test(id)||id.includes('..'))throw Error('Ungültiges Modell-Repository.');return id;}
function safeFile(name){if(typeof name!=='string'||name.startsWith('/')||name.split('/').some(x=>!x||x==='..'||x==='.')||name.includes('\\'))throw Error('Ungültiger Modell-Dateipfad.');return name;}
export async function scanFolders(folders){
 const models=[],errors=[],seen=new Set();let visited=0;
 async function walk(dir,depth){if(depth>12||++visited>25000)return;let root;try{root=await realpath(dir);if(seen.has(root))return;seen.add(root);const entries=await readdir(root,{withFileTypes:true});
 const files=entries.map(e=>e.name);const weights=files.filter(n=>n.endsWith('.safetensors'));
 if(files.includes('config.json')&&weights.length&&(files.includes('tokenizer.json')||files.includes('tokenizer.model'))){
  const config=JSON.parse(await readFile(path.join(root,'config.json'),'utf8'));const bytes=(await Promise.all(weights.map(async n=>(await stat(path.join(root,n))).size))).reduce((a,b)=>a+b,0);
  models.push({id:hash(root),name:path.basename(path.dirname(root))==='snapshots'&&path.basename(path.dirname(path.dirname(root))).startsWith('models--')?path.basename(path.dirname(path.dirname(root))).replace(/^models--/,'').replaceAll('--','/'):path.basename(root),path:root,format:'mlx',bytes,architecture:config.model_type||'',...suitability(bytes)});
 }
 for(const entry of entries){const p=path.join(root,entry.name);if(entry.name.startsWith('.')&&entry.name!=='.cache')continue;
 if(entry.name.endsWith('.gguf')){if(/(?:mmproj|projector)/i.test(entry.name))continue;const split=entry.name.match(/-(\d{5})-of-(\d{5})\.gguf$/);if(split&&split[1]!=='00001')continue;
 let bytes=(await stat(p)).size;if(split){const total=Number(split[2]);if(total>256)continue;for(let i=2;i<=total;i++)bytes+=(await stat(p.replace(/-00001-of-/,`-${String(i).padStart(5,'0')}-of-`))).size;}
 models.push({id:hash(p),name:entry.name.replace(/\.gguf$/,''),path:p,format:'gguf',bytes,...suitability(bytes)});
 }else if(entry.isDirectory()||entry.isSymbolicLink()){if(['blobs','.git','node_modules'].includes(entry.name))continue;if((await stat(p)).isDirectory())await walk(p,depth+1);}
 }
 }catch(e){errors.push({path:dir,message:e.code==='EACCES'?'Zugriff verweigert':e.code==='ENOENT'?'Ordner oder Modelldatei fehlt':e.message});}}
 for(const f of folders)await walk(f,0);return {models:models.sort((a,b)=>a.rank-b.rank||a.name.localeCompare(b.name)),errors,truncated:visited>25000};
}
async function json(url,signal){const r=await fetch(url,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000)});if(!r.ok)throw Error(r.status===401||r.status===403?'Modell benötigt eine Freigabe. Bitte zunächst auf Hugging Face herunterladen.':`Modellkatalog nicht erreichbar (HTTP ${r.status}).`);return r.json();}
export async function searchCatalog(query,format){if(!['gguf','mlx'].includes(format))throw Error('Format auswählen.');const u=new URL('https://huggingface.co/api/models');u.search=new URLSearchParams({search:String(query||'').slice(0,100),filter:format,sort:'downloads',direction:'-1',limit:'30',full:'true'});const rows=(await json(u)).filter(r=>!r.private&&!r.disabled).slice(0,12);
 const result=await Promise.all(rows.map(async r=>{const base={id:r.id,name:r.id.split('/').pop(),format,downloads:r.downloads||0,license:r.cardData?.license||'Lizenz auf Modellseite prüfen',url:'https://huggingface.co/'+r.id};try{const info=await catalogFiles(r.id,format);const candidate=format==='mlx'?{bytes:info.bytes,...suitability(info.bytes)}:recommendFile(info.files);return {...base,...candidate};}catch{return {...base,...suitability(0)};}}));return result.sort((a,b)=>a.rank-b.rank||b.downloads-a.downloads);}
export function recommendFile(files){const candidates=files.filter(f=>!/-0*(?:[2-9]|[1-9][0-9]+)-of-/.test(f.name)).map(f=>({...f,bytes:variantSize(files,f.name),...suitability(variantSize(files,f.name))}));candidates.sort((a,b)=>a.rank-b.rank||Number(!/Q4_K_M/i.test(a.name))-Number(!/Q4_K_M/i.test(b.name))||a.bytes-b.bytes);const c=candidates[0];return c?{bytes:c.bytes,fit:c.fit,rank:c.rank,suggestedFile:c.name}:suitability(0);}
export function variantSize(files,name){const split=name.match(/^(.*)-\d{5}-of-(\d{5})\.gguf$/);return split?files.filter(f=>f.name.startsWith(split[1]+'-')&&f.name.endsWith('-of-'+split[2]+'.gguf')).reduce((n,f)=>n+f.bytes,0):files.find(f=>f.name===name)?.bytes||0;}
export async function catalogFiles(repo,format,signal){safeRepo(repo);if(!['mlx','gguf'].includes(format))throw Error('Ungültiges Modellformat.');const doc=await json('https://huggingface.co/api/models/'+repo+'?blobs=true',signal);if(!/^[a-f0-9]{40}$/.test(doc.sha))throw Error('Modellversion nicht eindeutig.');const siblings=doc.siblings||[];
 let files=siblings.filter(f=>format==='gguf'?f.rfilename.endsWith('.gguf')&&!/(?:mmproj|projector)/i.test(f.rfilename):/\.(?:json|safetensors|model|txt|jinja|tiktoken)$/.test(f.rfilename));
 files=files.map(f=>({name:safeFile(f.rfilename),bytes:f.size||f.lfs?.size||0,sha:f.lfs?.sha256||null}));
 if(format==='mlx'&&(!files.some(f=>f.name==='config.json')||!files.some(f=>f.name.endsWith('.safetensors'))))throw Error('Keine unterstützte MLX-Modellstruktur gefunden.');
 const bytes=files.reduce((n,f)=>n+f.bytes,0);return {repo,revision:doc.sha,files:files.map(f=>({...f,variantBytes:variantSize(files,f.name)})),bytes,...suitability(bytes),license:doc.cardData?.license||'Lizenz auf Modellseite prüfen'};
}
export class LocalModels {
 constructor(data){this.data=data;this.home=path.join(data,'local-models');this.file=path.join(data,'local-models.json');this.config={folders:[]};this.models=[];this.errors=[];this.job=null;this.active=null;this.child=null;this.proxy=null;this.closing=false;}
 async init(){await mkdir(this.home,{recursive:true,mode:0o700});try{this.config=JSON.parse(await readFile(this.file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}const downloads=path.join(this.home,'models');await mkdir(downloads,{recursive:true});if(!this.config.folders.includes(downloads)){this.config.folders.unshift(downloads);await atomic(this.file,this.config);}await this.scan();}
 async scan(){const r=await scanFolders(this.config.folders);this.models=r.models;this.errors=r.errors;if(r.truncated)this.errors.push({path:'',message:'Suche auf 25.000 Ordner begrenzt. Bitte gezieltere Ordner wählen.'});return this.status();}
 async status(){const suggested=[];for(const p of [path.join(os.homedir(),'.lmstudio/models'),path.join(os.homedir(),'.cache/huggingface/hub'),path.join(os.homedir(),'Models')])if(!this.config.folders.includes(p)&&await exists(p))suggested.push(p);return {folders:this.config.folders,models:this.models,errors:this.errors,suggested,active:this.active,job:this.job,memory:os.totalmem(),arch:process.arch,platform:process.platform,backend:this.config.backend||'cpu',runtimes:{gguf:!!(await this.runtime('gguf')),mlx:!!(await this.runtime('mlx'))}};}
 async folder(source,remove=false){const p=remove?source:await realpath(source);if(remove&&!this.config.folders.includes(p))throw Error('Ordner nicht verbunden.');if(!remove&&!(await stat(p)).isDirectory())throw Error('Bitte einen Ordner wählen.');if(remove&&p===path.join(this.home,'models'))throw Error('Der Downloadordner bleibt in der Bibliothek.');this.config.folders=remove?this.config.folders.filter(x=>x!==p):[...new Set([...this.config.folders,p])];await atomic(this.file,this.config);return this.scan();}
 begin(label,action){if(this.job?.running)throw Error('Bitte den aktuellen Vorgang abwarten oder abbrechen.');this.controller=new AbortController();this.job={id:randomUUID(),label,running:true,done:0,total:0,error:''};const signal=this.controller.signal;this.promise=Promise.resolve().then(()=>action(signal)).then(()=>{this.job.running=false;this.job.label='Abgeschlossen';}).catch(e=>{this.job.running=false;this.job.error=signal.aborted?'Abgebrochen.':e.message;});return {ok:true};}
 cancel(){this.controller?.abort();return {ok:true};}
 async downloadFile(url,file,{signal,sha,max=200*GiB}={}){await mkdir(path.dirname(file),{recursive:true,mode:0o700});const r=await fetch(url,{signal});if(!r.ok)throw Error(`Download fehlgeschlagen (HTTP ${r.status}).`);let count=0;const h=createHash('sha256');const handle=await import('node:fs/promises').then(fs=>fs.open(file+'.part','w',0o600));try{for await(const b of r.body){signal?.throwIfAborted();count+=b.length;if(count>max)throw Error('Download überschreitet die erwartete Größe.');h.update(b);await handle.writeFile(b);if(this.job)this.job.done+=b.length;}if(sha&&h.digest('hex')!==sha)throw Error('Prüfsumme stimmt nicht. Download verworfen.');await handle.close();await rename(file+'.part',file);}catch(e){await handle.close().catch(()=>{});await rm(file+'.part',{force:true});throw e;}}
 async command(program,args,signal,extraEnv={}){await new Promise((resolve,reject)=>{const c=spawn(program,args,{windowsHide:true,env:{...process.env,...extraEnv,UV_PYTHON_INSTALL_DIR:path.join(this.home,'python'),UV_CACHE_DIR:path.join(this.home,'uv-cache')},stdio:['ignore','ignore','pipe'],signal});let err='';c.stderr.on('data',b=>err=(err+b).slice(-2000));c.once('error',reject);c.once('exit',code=>code===0?resolve():reject(Error('Engine-Einrichtung fehlgeschlagen: '+err.slice(-800))));});}
 async findFile(dir,name){if(!await exists(dir))return null;for(const e of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.name===name&&!e.isDirectory())return p;if(e.isDirectory()){const f=await this.findFile(p,name);if(f)return f;}}return null;}
 async runtime(format){if(!await exists(path.join(this.home,format+'.ready')))return null;return format==='mlx'?(await exists(path.join(this.home,'mlx/bin/python'))?path.join(this.home,'mlx/bin/python'):null):this.findFile(path.join(this.home,'gguf'),process.platform==='win32'?'llama-server.exe':'llama-server');}
 async setBackend(backend){if(!['cpu','vulkan'].includes(backend))throw Error('Unbekannte Engine');if(this.child||this.job?.running)throw Error('Modell zuerst entladen und Vorgang beenden.');if(this.config.backend!==backend){await rm(path.join(this.home,'gguf.ready'),{force:true});this.config.backend=backend;await atomic(this.file,this.config);}return this.status();}
 async install(format,signal){
 if(process.platform==='win32'){
  if(format!=='gguf')throw Error('MLX benötigt Apple Silicon. Unter Windows ein GGUF-Modell wählen.');
  if(process.arch!=='x64')throw Error('Die integrierte Windows-Engine ist für x64 gebaut.');
  if(await this.runtime(format))return;
  const source=this.config.backend==='vulkan'?runtimeSources.winVulkan:runtimeSources.winCPU;
  const archive=path.join(this.home,'gguf.zip'),destination=path.join(this.home,'gguf');
  this.job.label='Windows-GGUF-Engine einrichten …';
  await this.downloadFile(source.url,archive,{signal,sha:source.sha,max:100*1024**2});
  await rm(destination,{recursive:true,force:true});await mkdir(destination,{recursive:true});
  const powershell=path.join(process.env.SystemRoot||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe');
  await this.command(powershell,['-NoProfile','-NonInteractive','-Command',"$ErrorActionPreference='Stop'; Expand-Archive -LiteralPath $env:PI_DESK_ENGINE_ZIP -DestinationPath $env:PI_DESK_ENGINE_DEST -Force"],signal,{PI_DESK_ENGINE_ZIP:archive,PI_DESK_ENGINE_DEST:destination});
  if(!await this.findFile(destination,'llama-server.exe'))throw Error('Windows-Engine fehlt im Archiv.');
  await writeFile(path.join(this.home,'gguf.ready'),'llama.cpp b11013 '+(this.config.backend||'cpu'));await rm(archive,{force:true});return;
 }
 if(process.platform!=='darwin'||process.arch!=='arm64')throw Error('Die integrierten Engines benötigen einen Mac mit Apple Silicon.');if(await this.runtime(format))return;
 const kind=format==='gguf'?'gguf':'uv',source=runtimeSources[kind],archive=path.join(this.home,kind+'.tar.gz'),destination=path.join(this.home,kind);this.job.label=format==='gguf'?'GGUF-Engine laden …':'MLX-Engine einrichten …';await this.downloadFile(source.url,archive,{signal,sha:source.sha,max:500*1024**2});await mkdir(destination,{recursive:true});await this.command('/usr/bin/tar',['-xzf',archive,'-C',destination],signal);await rm(archive,{force:true});
 if(format==='mlx'){const uv=await this.findFile(destination,'uv');const venv=path.join(this.home,'mlx');try{await this.command(uv,['venv','--python','3.12','--managed-python',venv],signal);await this.command(uv,['pip','install','--python',path.join(venv,'bin/python'),'mlx-lm==0.31.3'],signal);}catch(e){await rm(venv,{recursive:true,force:true});throw e;}}
 await writeFile(path.join(this.home,format+'.ready'),format==='mlx'?'mlx-lm 0.31.3':'llama.cpp b11013');if(!await this.runtime(format))throw Error('Engine wurde nicht gefunden. Einrichtung erneut versuchen.');}
 async download(repo,format,filename,destination,signal,expectedRevision){const info=await catalogFiles(repo,format,signal);if(expectedRevision&&info.revision!==expectedRevision)throw Error('Die Modellversion hat sich geändert. Details neu öffnen und erneut auswählen.');let files=info.files;if(format==='gguf'){const chosen=files.find(f=>f.name===filename);if(!chosen)throw Error('Modelldatei nicht gefunden.');const split=filename.match(/^(.*)-\d{5}-of-(\d{5})\.gguf$/);files=split?files.filter(f=>f.name.startsWith(split[1]+'-')&&f.name.endsWith('-of-'+split[2]+'.gguf')):[chosen];}
 const targetRoot=await realpath(destination);if(!this.config.folders.includes(targetRoot))throw Error('Bitte einen verbundenen Modellordner wählen.');const total=files.reduce((n,f)=>n+f.bytes,0);if(!total||files.some(f=>!f.bytes))throw Error('Downloadgröße nicht verfügbar. Bitte später erneut versuchen.');const disk=await statfs(targetRoot);if(total+GiB>disk.bavail*disk.bsize)throw Error('Nicht genug freier Speicher im Zielordner.');
 const final=path.join(targetRoot,repo.replace('/','--')+'--'+info.revision.slice(0,8)+(format==='gguf'?'--'+hash(filename):''));if(await exists(final))throw Error('Dieses Modell liegt bereits im Zielordner. Bibliothek aktualisieren.');const stage=path.join(targetRoot,'.pi-download-'+randomUUID());await mkdir(stage,{mode:0o700});this.job.total=total;this.job.label='Modell herunterladen …';try{for(const f of files){signal.throwIfAborted();await this.downloadFile(`https://huggingface.co/${repo}/resolve/${info.revision}/${f.name.split('/').map(encodeURIComponent).join('/')}`,path.join(stage,f.name),{signal,sha:f.sha,max:f.bytes});if((await stat(path.join(stage,f.name))).size!==f.bytes)throw Error('Datei unvollständig.');}await rename(stage,final);await this.scan();}catch(e){await rm(stage,{recursive:true,force:true});throw e;}}
 async stop(){const child=this.child;this.child=null;this.active=null;if(this.proxy){this.proxy.closeAllConnections();await new Promise(r=>this.proxy.close(r));this.proxy=null;}if(child&&child.exitCode===null){child.kill('SIGTERM');await new Promise(r=>{const t=setTimeout(()=>{child.kill('SIGKILL');r();},4000);child.once('exit',()=>{clearTimeout(t);r();});});}}
 async start(id,signal){await this.scan();const model=this.models.find(x=>x.id===id);if(!model)throw Error('Modelldatei nicht mehr vorhanden. Bibliothek aktualisieren.');await this.install(model.format,signal);await this.stop();this.active={id:model.id,name:model.name,state:'loading',error:''};this.job.label='Modell in den Speicher laden …';
 const port=await new Promise((resolve,reject)=>{const s=net.createServer();s.on('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});const key=randomBytes(32).toString('hex');const runtime=await this.runtime(model.format);
 const args=model.format==='gguf'?['--model',model.path,'--host','127.0.0.1','--port',String(port),'--alias','local','--ctx-size','8192','--jinja','--api-key',key,...(process.platform==='win32'?['--n-gpu-layers',this.config.backend==='vulkan'?'99':'0']:[])]:['-m','mlx_lm.server','--model',model.path,'--host','127.0.0.1','--port',String(port)];
 const child=spawn(runtime,args,{windowsHide:true,cwd:path.dirname(model.path),env:{...process.env,HF_HUB_OFFLINE:'1',TRANSFORMERS_OFFLINE:'1',TOKENIZERS_PARALLELISM:'false'},stdio:['ignore','ignore','pipe']});this.child=child;let log='',failure='';child.stderr.on('data',b=>log=(log+b).slice(-4000));child.on('error',e=>failure=e.message);child.on('exit',code=>{if(this.child===child&&this.active){this.active.state='error';this.active.error=failure||`Engine beendet (${code}). ${log.slice(-500)}`;}});
 try{const deadline=Date.now()+180000;let ready=false;while(Date.now()<deadline){signal.throwIfAborted();if(failure||child.exitCode!==null)throw Error(failure||'Modell konnte nicht geladen werden: '+log.slice(-700));try{const r=await fetch(`http://127.0.0.1:${port}/v1/models`,{headers:{Authorization:'Bearer '+key},signal:AbortSignal.timeout(1000)});if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,250));}if(!ready)throw Error('Modellstart dauert zu lange. Ein kleineres Modell versuchen.');
 // App-owned gateway pins the model and accepts only authenticated model API traffic.
 this.proxy=http.createServer(async(req,res)=>{if(req.headers.authorization!=='Bearer '+key){res.writeHead(401);res.end();return;}if(req.url==='/v1/models'&&req.method==='GET'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{id:'local',object:'model'}]}));return;}if(req.url!=='/v1/chat/completions'||req.method!=='POST'){res.writeHead(404);res.end();return;}try{let raw='';for await(const b of req){raw+=b;if(raw.length>4000000)throw Error('Kontext zu groß.');}const input=JSON.parse(raw);input.model=model.format==='gguf'?'local':model.path;delete input.adapters;delete input.draft_model;input.max_tokens=Math.min(Number(input.max_tokens)||2048,4096);const abort=new AbortController();res.on('close',()=>abort.abort());const upstream=await fetch(`http://127.0.0.1:${port}/v1/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify(input),signal:abort.signal});res.writeHead(upstream.status,{'Content-Type':upstream.headers.get('content-type')||'application/json'});for await(const chunk of upstream.body){if(!res.write(chunk))await new Promise(r=>res.once('drain',r));}res.end();}catch(e){if(!res.headersSent)res.writeHead(502);res.end(JSON.stringify({error:{message:e.message}}));}});
 await new Promise((resolve,reject)=>{this.proxy.once('error',reject);this.proxy.listen(0,'127.0.0.1',resolve);});this.active.state='ready';return {name:model.name.slice(0,80),kind:'openai',baseUrl:`http://127.0.0.1:${this.proxy.address().port}/v1`,models:['local'],apiKey:key};
 }catch(e){await this.stop();throw e;}}
 async close(){this.closing=true;this.cancel();await this.promise?.catch(()=>{});await this.stop();}
}
